version: '3'

services:
  nginx:
    image: nginx:1.15.9
    container_name: ng
    ports:
      - "9999:8080"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - api

  api:
    build: .
    restart: unless-stopped
    container_name: api
    command: ['./scripts/run_server.sh']
    volumes:
      - .:/src
    expose:
      - "8080"
